config/routes.rb
Rails.application.routes.draw do
  get '/api/throw', to: 'game#throw'
  resources :tools do
    post 'set_beaten_tool', on: :member
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "game#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_and_belongs_to_many :tools_that_this_can_beat,
                          class_name: "Tool",
                          join_table: 'which_tool_beats_whats',
                          foreign_key: "tool_that_beats_id",
                          association_foreign_key: "tool_that_is_beaten_id"
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [139, 139]
  end

  validates :name, presence: true
  validate :image_type

  def beats?(other_tool)
    tools_that_this_can_beat.include?(other_tool)
  end

  private

  def image_type
    if image.attached? == false
      errors.add(:image, "is missing!")
    end
    unless image&.content_type&.in?(%('image/jpeg image/png image/svg+xml'))
      errors.add(:image, "needs to be a jpeg, png or svg!")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActiveStorage::SetCurrent
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def home
    @tools = Tool.all.with_attached_image
  end

  def throw
    player_tool = Tool.find_by(name: params[:tool_name])
    curb_tool = GetCurbsTool.call
    winner = DetermineWinner.call(player_tool:, curb_tool:)

    render json: { curbTool: curb_tool.name, winner: winner }
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: %i[ show edit update destroy set_beaten_tool ]


  # GET /tools or /tools.json
  def index
    @tools = Tool.all
  end

  # GET /tools/1 or /tools/1.json
  def show
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
    @other_tools = Tool.all.includes(:tools_that_this_can_beat).excluding(@tool)
  end

  # PUT /tools/1/set_beaten_tool

  def set_beaten_tool
    selected_tool = Tool.find(params['selected_tool_id'])
    if params['selected']
      @tool.tools_that_this_can_beat.push(selected_tool)
    else
      @tool.tools_that_this_can_beat.delete(selected_tool)
    end

    render plain: 'ok',   status: :ok
  end

  # POST /tools or /tools.json
  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to tools_url, notice: "Tool was successfully created." }
        format.json { render :index, status: :created, location: @tool }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1 or /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to tools_url, notice: "Tool was successfully updated." }
        format.json { render :index, status: :ok, location: @tool }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1 or /tools/1.json
  def destroy
    @tool.destroy

    respond_to do |format|
      format.html { redirect_to tools_url, notice: "Tool was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tool
    @tool = Tool.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tool_params
    params.require(:tool).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/game/home.html.erb
<h1 id="page-title">ROCK – PAPER – SCISSORS</h1>
<p id="description">Rock Paper Scissors is a zero sum game that is usually played by two people using their hands and no
  tools. The idea
  is to make shapes with an outstretched hand where each shape will have a certain degree of power and will lead to an
  outcome.</p>
<h2 id="prompt">SELECT YOUR BET</h2>
<div id="tool-grid">
  <% @tools.each do |tool| %>
    <div class="tool-option" onclick="<%= "chooseTool('#{tool.name}')" %>">
      <%= image_tag tool.image.variable? ? tool.image.variant(:thumb) : tool.image, id: "#{tool.name}-image" %>
      <span class="name"><%= tool.name.capitalize %></span>
    </div>
  <% end %>
</div>

<div id="backdrop" class="hidden" onclick="closePopups()"></div>
<div id="popup" class="hidden">

  <div id="header">
    WAITING CURB’S CHOOSE
  </div>
  <div id=popup-grid>
    <%= image_tag '', id: 'your-choice' %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 10">
      <defs>
        <style>.a, .b, .c {
            fill: #36006c;
        }

        .b {
            opacity: 0.54;
        }

        .c {
            opacity: 0.12;
        }</style>
      </defs>
      <g transform="translate(-857 -454)">
        <circle class="a" cx="5" cy="5" r="5" transform="translate(857 454)"/>
        <circle class="b" cx="5" cy="5" r="5" transform="translate(884 454)"/>
        <circle class="c" cx="5" cy="5" r="5" transform="translate(911 454)"/>
      </g>
    </svg>
    <span id="your-bet">Your bet</span>
    <%= image_tag 'curb_logo.png', id: 'curb-logo' %>
  </div>
  <%= image_tag 'close.png', id: 'close', onclick: "closePopup()" %>
</div>

<div id="result" class="hidden">
  <div id="panel">
    <span id="result-title">You lost!</span>
    <span id="result-details">Curb with paper wins</span>
    <%= image_tag '', id: 'curbs-choice' %>
    <button id="ok" onclick="closeResult()">Ok</button>
  </div>
  <%= image_tag 'close.png', id: 'close', onclick: "closeResult()" %>
</div>

app/views/game/throw.html.erb
<h1>Game#throw</h1>
<p>Find me in app/views/game/throw.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RockPaperScissors</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&family=Roboto&display=swap" rel="stylesheet">
  <%= javascript_importmap_tags %>
</head>

<body>
<main>
  <%= yield %>
</main>
</body>
</html>

app/views/tools/_form.html.erb
<%= form_with(model: tool) do |form| %>
  <% if tool.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
        <% tool.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
      </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tools/_tool.html.erb
<div id="<%= dom_id tool %>">
  <p>
    <strong>Name:</strong>
    <%= tool.name %>
  </p>

</div>

app/views/tools/edit.html.erb
<h1>Editing tool</h1>

<%= render "form", tool: @tool %>
<label>This tool beats</label>
<div id="tool-grid">
  <% @other_tools.each do |tool| %>
    <div class="tool-option" data-controller="tool"
         data-tool-current-tool-id-value="<%= @tool.id %>"
         data-tool-selected-tool-id-value="<%= tool.id %>"
         data-tool-selected-value="<%= @tool.beats?(tool) %>"
         data-tool-target="element"
         data-action="click->tool#togleSelecetdState">
      <%= image_tag tool.image.variable? ? tool.image.variant(:thumb) : tool.image.url, id: "#{tool.name}-image" %>
      <span class="name"><%= tool.name.capitalize %></span>
    </div>
  <% end %>
</div>

<br>

<div>
  <%= link_to "Back to tools", tools_path %>
</div>

app/views/tools/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tools</h1>

<div id="tools">
  <% @tools.each do |tool| %>
    <%= render tool %>
    <p>
      <%= link_to "Edit this tool", edit_tool_path(tool) %>
    </p>
  <% end %>
</div>

<%= link_to "New tool", new_tool_path %>

app/views/tools/new.html.erb
<h1>New tool</h1>

<%= render "form", tool: @tool %>

<br>

<div>
  <%= link_to "Back to tools", tools_path %>
</div>

app/views/tools/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tool %>

<div>
  <%= link_to "Edit this tool", edit_tool_path(@tool) %> |
  <%= link_to "Back to tools", tools_path %>

  <%= button_to "Destroy this tool", @tool, method: :delete %>
</div>